<head>
  <link rel="stylesheet" href="styles/master.css">
  <meta charset="utf-8">
  <title><?php print($title) ?></title>
  <meta name="description" content="Apache details and facts">
  <meta name="keywords" content="PHP, SQL, Management, Apache, Info, Details, Facts, Server">
  <meta name="author" content="Nicholas, Yash, Syed, Chris">
  <link rel="shortcut icon" href="img/favicon.ico">
</head>
